using UnityEngine;

public class GlobalAudioManager : MonoBehaviour {
    private static GlobalAudioManager _instance;

    public static GlobalAudioManager Instance {
        get {
            if (_instance == null) {
                _instance = FindObjectOfType<GlobalAudioManager>();
                if (_instance == null) {
                    GameObject go = new GameObject("GlobalAudioManager_AutoGenerated");
                    _instance = go.AddComponent<GlobalAudioManager>();
                    go.AddComponent<AudioSource>();
                    DontDestroyOnLoad(go);
                }
            }
            return _instance;
        }
    }

    private AudioSource audioSource;

    void Awake() {
        if (_instance == null) {
            _instance = this;
            audioSource = GetComponent<AudioSource>();
            if (audioSource == null) audioSource = gameObject.AddComponent<AudioSource>();
            DontDestroyOnLoad(gameObject);
        } else if (_instance != this) {
            Destroy(gameObject);
        }
    }

    public void PlayGlobalSound(AudioClip clip, float volume = 1f) {
        if (clip != null) {
            if (audioSource == null) audioSource = GetComponent<AudioSource>();
            audioSource.PlayOneShot(clip, volume);
        }
    }

    public void PlaySoundSegment(AudioClip clip, float startTime, float duration, float volume = 1f) {
        if (clip == null) return;

        GameObject tempGO = new GameObject("TempAudio");
        AudioSource source = tempGO.AddComponent<AudioSource>();
        source.clip = clip;
        source.volume = volume;
        source.time = startTime;
        source.Play();
    
        Destroy(tempGO, duration);
        DontDestroyOnLoad(tempGO); 
    }
}
